spring:
  application:
    name: employee-service
    data:
      mongodb:
        uri: mongodb://localhost:27017/companyDB
    server:
      port: 8080

logging:
  level:
    org.springframework.data.mongodb.core.MongoTemplate: DEBUG
    org.springframework.data.mongodb.repository.query: DEBUG
